@startuml pathfinding_aStar

skinparam shadowing false

skinparam Arrow {
    Color black
}

<style>
.Physical {

}
.HAL {
    BackgroundColor #ff9933
}
.Application {
    BackgroundColor palegreen
}
</style>

component "2x AAA batteries" as batt
component "Reverse polarity protection" as rev

batt -> rev

component "Micro Controller" as uc

batt -[hidden]down-> uc
rev --> uc : Powers

component "LCD TouchScreen display" as lcd

rev --> lcd : Powers
uc -> lcd : Drives
lcd -> uc : Touch

component "Multiplayer Port" as multi

uc -down-> multi
multi --> uc

component "Speaker" as hp

uc -left-> hp

component "Ambiant light sensor" as ldr

multi -[hidden]right->ldr
ldr --> uc

@enduml
